global:
  resolve_timeout: 5m
  smtp_from: ''
  smtp_smarthost: ''
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 10m
  receiver: 'email-notifications'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: ''
    send_resolved: true
    headers:
      subject: '{{ .GroupLabels.alertname }}'
    html: |
      {{ range .Alerts }}
        <h3>{{ .Labels.alertname }}</h3>
        <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
        <p><strong>Instance:</strong> {{ .Labels.instance }}</p>
        <p><strong>Description:</strong> {{ .Annotations.description }}</p>
        <p><strong>Value:</strong> {{ .Annotations.value }}</p>
        <p><strong>Started:</strong> {{ .StartsAt }}</p>
      {{ end }}