global:
  scrape_interval: 5s
  evaluation_interval: 5s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - ''
rule_files:
  - stress_rules.yml
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - ''
  - job_name: node_exporter
    static_configs:
      - targets:
          - 'vm1:9100'
  - job_name: mysql_exporter
    static_configs:
      - targets:
          - 'vm1:9104'
